### ISSUE TITLE
[GENERAL] vore belly turned out to be united for everyone

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TS-Rogue-Star/Rogue-Star#170]
#### Brief description of the bug
Vore bellies have for some reason combined for all characters, regardless of the new or old character

#### What you expected to happen
Each character has different settings of vore belly

#### What actually happened
vore belly turned out to be united for everyone

#### Code Revision
Server revision: B:release D:
Commit: [bdbfcb8d9c5488e0473a1fefabef762e1420936a](http://127.0.0.1:14812/tmp8576/%3Ca%20href=%22https://github.com/TS-Rogue-Star/Rogue-Star/commit/bdbfcb8d9c5488e0473a1fefabef762e1420936a%22%3Ehttps://github.com/TS-Rogue-Star/Rogue-Star/commit/bdbfcb8d9c5488e0473a1fefabef762e1420936a%3C/a%3E)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by lm40** [comment]
Well as far as I can tell across three of your four characters your vore bellies are actually the same, how did this come to pass? It never happened to me so I will need steps to reproduce.

**Comment by lm40** [comment]
If you make new characters they do copy bellies of existing characters, I will need steps to reproduce in order to prove that this is actually unintended behavior
